version: "3"
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-vanilla-latest
    ports:
      - "25565:25565"
      - "8865:8123"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      VERSION: "LATEST"
      TYPE: "PAPER"
      ENABLE_AUTOPAUSE: "TRUE"
      TZ: "Europe/Bratislava"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "java-rcon-pass"
      # RCON_PORT: 28016
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "http://localhost:3306"
      CFG_DB_NAME: "mc-vanilla-latest"
      CFG_DB_USER: "mc-user"
      CFG_DB_PASSWORD: "mc-pass"
      # JAVA config
#      INIT_MEMORY: "128M"
#      MAX_MEMORY: "2G"
      MEMORY: "1G"
      USE_AIKAR_FLAGS: "true"
      GUI: "false"
      #server.properties
#     LEVEL_SEED: -895041041
      GAMEMODE: survival
      DIFFICULTY: "normal"
#      OPS: "XXXXXX"
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000
      SERVER_NAME: "Home - MC-Vanilla -latest"
      MOTD: "Home - MC-Vanilla -latest"
    restart: unless-stopped
    stdin_open: true
    tty: true