version: '3.4'
services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock-latest
    environment:
      EULA: "TRUE"
      LEVEL_SEED: -895041041
      GAMEMODE: survival
      DIFFICULTY: "normal"
#      OPS: "XXXXXX"
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000
      SERVER_NAME: "Home - MC-Bedrock -latest"
      MOTD: "Home - MC-Bedrock -latest"
      ALLOW_CHEATS: "true"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true