---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Bratislava
    volumes:
      - ./data:/config
    ports:
      - "8091:80"
      - "8092:443"
    restart: unless-stopped