%YAML 1.1
---
worlds:
-   sealevel: 63
    nether: false
    name: world
    the_end: false
    title: world/overworld
    height: 256
-   sealevel: 63
    nether: true
    name: DIM-1
    the_end: false
    title: world/the_nether
    height: 256
-   sealevel: 63
    nether: false
    name: DIM1
    the_end: true
    title: world/the_end
    height: 256
-   sealevel: 80
    nether: false
    name: DIM-23
    the_end: false
    title: world/midnight
    height: 256
-   sealevel: 63
    nether: false
    name: DIM418
    the_end: false
    title: world/tartarus
    height: 256
-   sealevel: 63
    nether: false
    name: DIM50
    the_end: false
    title: world/The Abyssal Wasteland
    height: 256
-   sealevel: 63
    nether: false
    name: DIM51
    the_end: false
    title: world/The Dreadlands
    height: 256
-   sealevel: 63
    nether: false
    name: DIM52
    the_end: false
    title: world/Omothol
    height: 256
-   sealevel: 63
    nether: false
    name: DIM53
    the_end: false
    title: world/The Dark Realm
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-11325
    the_end: false
    title: world/Deep Dark
    height: 256
-   sealevel: 63
    nether: false
    name: DIM66
    the_end: false
    title: world/EREBUS
    height: 256
-   sealevel: 63
    nether: false
    name: DIM2
    the_end: false
    title: world/frozennether
    height: 256
-   sealevel: 0
    nether: false
    name: DIM3
    the_end: false
    title: world/Aether
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-28982081
    the_end: false
    title: world/labyrinth
    height: 256
-   sealevel: 63
    nether: false
    name: DIM17
    the_end: false
    title: world/atum
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-6
    the_end: false
    title: world/MINING_WORLD
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-8
    the_end: false
    title: world/Ratlantis
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-11
    the_end: false
    title: world/Storage Cell
    height: 256
-   sealevel: 65
    nether: false
    name: DIM-9999
    the_end: false
    title: world/ExtraUtils2_Quarry_Dim
    height: 256
-   sealevel: 63
    nether: false
    name: DIM684
    the_end: false
    title: world/limbo
    height: 256
-   sealevel: 63
    nether: false
    name: DIM685
    the_end: false
    title: world/private_pockets
    height: 256
-   sealevel: 63
    nether: false
    name: DIM-343800852
    the_end: false
    title: world/Spectre
    height: 256
-   sealevel: 63
    nether: false
    name: DIM686
    the_end: false
    title: world/public_pockets
    height: 256
-   sealevel: 63
    nether: false
    name: DIM687
    the_end: false
    title: world/dungeon_pockets
    height: 256
isMCPC: false
useSaveFolderAsName: true
maxWorldHeight: 256
