version: "3"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=localhost:3306
      - DB_NAME=table_name
      - DB_USER=user
      - DB_PASSWD=user_pass
    restart: unless-stopped
#    network_mode: host
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3003:3000"
      - "222:22"