version: '3'
services:
  mosquitto:
    image: toke/mosquitto
    container_name: mosquitto
    environment:
      - PUID=1883
      - PGID=1883
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/mqtt/config:rw
      - ./data:/mqtt/data:rw
      - ./logs:/mqtt/log:rw
    network_mode: host
    privileged: true
    restart: unless-stopped