---
version: "2.1"
services:
  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Bratislava
      - CONTEXT_PATH=music.mydomain.com #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
#      - </path/to/config>:/config
#      - </path/to/music>:/music
#      - </path/to/playlists>:/playlists
#      - </path/to/podcasts>:/podcasts
#      - </path/to/other media>:/media #optional
      - "./data:/config"
      - "/media/3tb/Media/Music:/data/music"
      - "/media/3tb/Media/Playlists:/data/playlists"
      - "/media/3tb/Media/Podcasts:/data/podcasts"
    ports:
      - 4040:4040
#    devices:
#      - /dev/snd:/dev/snd #optional
    restart: unless-stopped