version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./data:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Bratislava
    restart: always
    network_mode: host
    ports:
      - "8123:8123"
  hass-configurator:
    container_name: hass-configurator
    image: "causticlab/hass-configurator-docker:x86_64"
    restart: always
    ports:
      - "3218:3218/tcp"
    network_mode: host
    volumes:
      - "./hass-configurator-config:/config"
      - "./data:/hass-config"