version: "2"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole63
    image: pihole/pihole:latest
    ports:
      - "63:53/tcp"
      - "63:53/udp"
      # - "67:67/udp"
      - "86:80/tcp"
      # - "443:443/tcp"
    environment:
      TZ: 'Europe/Bratislava'
      WEBUIBOXEDLAYOUT: traditional
      SKIPGRAVITYONBOOT: 0
      WEBPASSWORD: 'pihole-Pass'
    # Volumes store your data between container upgrades
    volumes:
      - '/var/containers.d/pihole63/etc-pihole/:/etc/pihole/'
      - '/var/containers.d/pihole63/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped