version: '3.5'
services:
  adminer:
    container_name: adminer
    image: edyan/adminer
    restart: unless-stopped
    networks:
      - mariadb
#    volumes:
#      - /var/containers.d/adminer/data:/app
    ports:
      - "8080:80"
networks:
  mariadb:
    name: mariadb