---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Bratislava
      - UMASK_SET=<022> #optional
    volumes:
      - "./data:/config"
      - "/media/3tb/Media/Music:/data/music"
      - "/media/3tb/Media/TV shows:/data/tvshows"
      - "/media/4tb/Media/Movies:/data/movies"
#      - "/opt/vc/lib:/opt/vc/lib" #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
#    devices:
#      - /dev/dri:/dev/dri #optional
#      - /dev/vcsm:/dev/vcsm #optional
#      - /dev/vchiq:/dev/vchiq #optional
#      - /dev/video10:/dev/video10 #optional
#      - /dev/video11:/dev/video11 #optional
#      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped