version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:alpine
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Bratislava
    restart: always
#    network_mode: host
    ports:
      - "9000:9000"
