version: "3"
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server:multiarch
    container_name: mc-modded-the1122pack
    ports:
      - "25566:25565"
      - "8866:8123"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      TYPE: "FTB"
      FTB_SERVER_MOD: "http://solder.endermedia.com/repository/downloads/the-1122-pack/the-1122-pack_1.2.2.zip"
      ENABLE_AUTOPAUSE: "TRUE"
      TZ: "Europe/Bratislava"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "mc-java-rcon-pass"
      # RCON_PORT: 28016
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "http://localhost:3306"
      CFG_DB_NAME: "mc-java-the1122pack"
      CFG_DB_USER: "mc-user"
      CFG_DB_PASSWORD: "mc-pass"
      # JAVA config
#      INIT_MEMORY: "128M"
#      MAX_MEMORY: "3G"
      MEMORY: "3G"
      USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
      #server.properties
      # LEVEL_SEED: -895041041
      GAMEMODE: survival
      DIFFICULTY: "normal"
#      OPS: "XXXXXX"
      MAX_PLAYERS: 6
      MAX_WORLD_SIZE: 1000000
      ONLINE_MODE: "FALSE"
      VIEW_DISTANCE: 8
      SERVER_NAME: "Home - MC-Modded -the-1.12.2-pack"
      MOTD: "Home - MC-Modded -the-1.12.2-pack"
    restart: unless-stopped
    stdin_open: true
    tty: true